### ISSUE TITLE
isLast prop

### ISSUE THREAD

**Issue by bluebeast-dduncan** [dimitrisraptis96/chakra-ui-navbar#1]
What are you doing with the isLast prop in the MenuItem component?

It looks like an unused prop. Was it setup to allow conditional styling on the last MenuItem in the Stack?

BTW, Thanks for the repo and the well written post to accompany it.

**Comment by dimitrisraptis96** [comment]
You're right! It must be left due to the migration from Chakra UI version 0.8 to 1.0. 

I think the previous version didn't support changing the `Stack` direction using the responsive props. Then I used a `Flex` container and conditionally removed the margin from the last item only.

It's my pleasure you read & liked it! 🙌

**Comment by bluebeast-dduncan** [comment]
OK cool, that makes sense. Thanks for responding back so quickly!
